title: nickxma
author: the thought stream that poses as me
email: nickxma@gmail.com
url: "https://nickxma.github.io"
baseurl: "" # Leave this empty if your site should not use a subpath
description: >
  A (nearly) no-CSS, fast, minimalist Jekyll theme.

permalink: /:slug.html

favicon: "logo.png"

remote_theme: nickxma/no-flex

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed